### ISSUE TITLE
Error: parse error at (buildbuddy-enterprise/templates/ingress.yaml:1): unclosed action

### ISSUE THREAD

**Issue by mortya** [buildbuddy-io/buildbuddy-helm#46]
The latest version of the helm chart as of this writing, 0.0.184, gives the following error:
`Error: parse error at (buildbuddy-enterprise/templates/ingress.yaml:1): unclosed action`
If I specify version 0.0.183 instead, I don't get this error.

This is with helm v3.5.3 and a values file that doesn't set ingress.

**Comment by sluongng** [comment]
@mortya do you still face the issue reported here? Should we close this?

**Comment by sluongng** [comment]
gona close this now due to inactivity. Please let me know if this is still happening.
