### ISSUE TITLE
Support the configuration of sensitive data using existing Kubernetes secrets

### ISSUE THREAD

**Issue by rszamszur** [buildbuddy-io/buildbuddy-helm#90]
Hello BuildBuddy Team,

I am reaching out to discuss an enhancement proposal for the Helm charts. Currently, these charts require secrets to be provided within the `values.yaml` file. This approach, while functional, it adds an extra layer of complexity and maintenance overhead. This complexity becomes particularly evident in situations such as:

- When an organization has specific requirements or methods for managing secrets.
- When there are limitations or issues with third-party solutions, for instance: [ArgoCD + helm-secrets](https://github.com/argoproj/argo-cd/issues/11866).
- When applying GitOps practices - ensuring data is encrypted at rest but still accessible by the GitOps controller.

I would like to propose a feature request to enhance the Helm charts to support the use of existing Kubernetes secrets. The ideal implementation of this feature would cater to any sensitive information that can currently be configured through value files.

I am keen to contribute to the development of this feature if it aligns with your project's goals. Could you please share any specific guidelines or requirements for such contributions? I would greatly appreciate any feedback or direction you could provide to help me proceed with this implementation.

For reference, I have included links to example open-source charts that support using existing k8s secrets to some extent:

- [Bitnami PostgreSQL Chart](https://github.com/bitnami/charts/blob/18f113584fe8f58113f4c810ddafc5f74c274001/bitnami/postgresql/values.yaml#L155-L158)
- [Coder Helm Chart](https://github.com/coder/coder/blob/24135a2d0f70d603985e1f3f83b0633f91ded0a7/helm/coder/values.yaml#L34-L35)
- [GitHub Actions Runner Controller Chart](https://github.com/actions/actions-runner-controller/blob/d515b4a6e0ae8e4008af4452732cb4103117f5bd/charts/gha-runner-scale-set/values.yaml#L16-L23)

Have a good one!

**Comment by rszamszur** [comment]
> Thanks for the proposal - would specifying our config options as environment variables work for your use-case? https://www.buildbuddy.io/docs/config#environment-variables

I must have overlooked that bit of documentation. At the first glance, seems like it could be sufficient. I'll test it tomorrow and update you on the results.

**Comment by siggisim** [comment]
Great, let us know if you run into any issues. We're happy to help!
