### ISSUE TITLE
Tag 2.64.0 is absent in all buildbuddy images 

### ISSUE THREAD

**Issue by farcop** [buildbuddy-io/buildbuddy-helm#97]
So all latest charts failed with default images.

**Comment by siggisim** [comment]
cc @iain-macdonald and @sluongng 

We ran into some issues with a new docker version on this release - which probably explains the missing images.

We'll get this sorted out and ping this issue when it's fixed.

**Comment by iain-macdonald** [comment]
Thanks for the report, farcop! Like Siggi said, we ran into some issues with the 2.64.0 release. I went ahead and cut and pushed a new 2.65.0 release and verified that the container images were tagged and pushed to gcr correctly, so you should be able to use that one. Sorry for the inconvenience!
